[build]
  publish = "site"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Pretty URLs for app folders (no trailing .html needed)
[[redirects]]
  from = "/caregiver"
  to = "/caregiver/"
  status = 301
  force = true

[[redirects]]
  from = "/divorce"
  to = "/divorce/"
  status = 301
  force = true

[[redirects]]
  from = "/small-estate"
  to = "/small-estate/"
  status = 301
  force = true

[[redirects]]
  from = "/nursing-appeal"
  to = "/nursing-appeal/"
  status = 301
  force = true
