[build]
  publish = "site"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  publish = "site"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
